### ISSUE TITLE
library Name  is confusing

### ISSUE THREAD

**Issue by ynnk** [patrickfuller/jgraph#1]
Hi i looked over your implmentation of graph vizualisation. good job so far 

One point , the names you use is very confusing.
Cause you have a package named igraph so a js lib names igraph.
there is also a library in C with python bindings named Igraph 
The igraph library for complex network research @  http://igraph.sourceforge.net/‎
It s a great tool that should not be confused with your project .

I ve also made implementation of graph visualisation using three.js as the renderer  and only used the Canvas renderer so far .

We also use massivelly the igraph library for graph manipulation before sending the data to the renderer. 
we compute our own layout and apply some community detection algorythms on the server side before sending the data to the client

you can see a demo a demo running over a synonyms graph in french , english an mandarin @ http://naviprox.net/tmuse/Wordnet_V?q=level
Use the links at the bottom to switch to the translations graphs or other language.

We also planed to use it with notebook ( which is to me one of the best tool available since years ) i used a forked version of the ipython notebok to include the js libs we wrote. i will take look at your way of embedding the javascript which seems better than i did .

Once again it s a good start, I stay tuned at your project 
Ynnk.

**Comment by patrickfuller** [comment]
I finally renamed this library, so this issue is resolved.

**Comment by ynnk** [comment]
:)
