### ISSUE TITLE
Node name

### ISSUE THREAD

**Issue by DaniilTitov** [patrickfuller/jgraph#11]
Hello, how do I make the name Node? As in this example:
http://patrickfuller.github.io/jgraph/examples/github.html

**Comment by patrickfuller** [comment]
Check out the source code of the example.

 * [github.json](https://github.com/patrickfuller/jgraph/blob/master/examples/github.json) shows where the name is in the data file
 * [this part of github.html](https://github.com/patrickfuller/jgraph/blob/master/examples/github.html#L44-L58) shows how `onEnter` and `onExit` are set to show a div with the node's `name` property

Hope this helps!

**Comment by DaniilTitov** [comment]
Is there any way to change this in the Python code?
For example, [here it is](http://patrickfuller.github.io/jgraph/examples/ipython.html) (second graph)

**Comment by patrickfuller** [comment]
It's currently javascript only, but you can run custom javascript in the notebook. It'd look like

```python
from IPython.display import Javascript
Javascript('jgraph.onEnter = function () { # new function here }')
```

where you could define the behavior from there. You can try copying from the example to see if the floating div approach works in the notebook.

**Comment by DaniilTitov** [comment]
Thank you, you really helped.
Can I ask one more question:
In each person I have field "user_id". With help this field I open page in social network. 
How I can change [this code](https://github.com/patrickfuller/jgraph/blob/master/examples/github.html#L66-L69) to do it?
![2017-05-10 0 49 37](https://cloud.githubusercontent.com/assets/16158330/25874662/314bbd36-351c-11e7-8985-4dba862f20cf.png)

**Comment by patrickfuller** [comment]
It's hard for me to say without knowing more about your project, but my first guess would be to replace `node.name` with `node.user_id`. If your social network is not github, you'll also have to change the rest of the URL.

Hope this helps!

**Comment by DaniilTitov** [comment]
Thank you!
