### ISSUE TITLE
Save graph

### ISSUE THREAD

**Issue by EntilZha** [patrickfuller/jgraph#6]
Is there an easy way to save a graph while in a notebook? I can't seem to find a method or way in the ipython interface

**Comment by patrickfuller** [comment]
There isn't currently, but I've already written the code to do this for another project. I'll release a new version with the save functionality in the coming days (probably tomorrow night).

**Comment by patrickfuller** [comment]
I added this functionality. Use the `show_save` arg to display a save icon.

![jgraph image save](https://cloud.githubusercontent.com/assets/1449833/12279816/2a84cf8c-b94f-11e5-87c8-c2d94ca9ea46.png)

Let me know if it works for you.

**Comment by EntilZha** [comment]
Tested and works great. Will take a look more at source code to see how it works
